name: kendsign
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6148394064512104
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4b4e4d'
    - '#958989'
    - '#da3d10'
    - '#fbf840'
    - '#3c1008'
  brandStrength: 0
  lightness: 0
  saturation: 0.4759012886788696
  rhythmicContrast: 0.75
purpose: []
